name: Rest Api Execution Performance

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: string
        description: 'testSuite'
        required: true
        default: 'restApi.RestApiTest'
      concurrent:
        type: string
        description: 'Quantity of users'
        required: true
        default: '10'

jobs:
  execrestapi:
    runs-on: ubuntu-latest
    name: Execution Performance Rest API
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'  

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute test
        run: gradle gatlingRun --simulation=${{ inputs.testSuite }} -DconcurrentUsers=${{ inputs.concurrent }}

      - name: Save report
        if: ${{always()}}
        uses: actions/upload-artifact@v3.1.2
        with:
          name: gatling report
          path: ./build/reports/gatling
      - name: "Publish test results"
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build/reports/gatling'
          keep_files: true
          user_name: Quino92
          user_email: jose.rioja.22@gmail.com
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./build/reports/gatling
